version: '3.4'

services:

  oracle:
    build: oracle
    image: oracle:11-xe
    container_name: oracle
    ports:
      - "1521:1521"
    environment:
      MSSQL_SA_PASSWORD: Forever21!
      ACCEPT_EULA: Y
    volumes:
      - .:/usr/local/src

  yopsql:
    depends_on:
      - oracle
    build: java
    image: yopsql:java
    container_name: yopsql
    volumes:
      - .:/usr/local/src
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /usr/local/src

